apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  namespace: docker-test
  labels:
    app: calculator
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 0
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
        label: label
    spec:
      containers:
        - name: calculator
          image: 192.168.56.31:443/dockeruser/calculator:chahing
          ports:
            - containerPort: 8090
          readinessProbe:
            httpGet:
              path: /sum?a=1&b=2
              port: 8090
      imagePullSecrets:
        - name: registry-secret